version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pomodoro-backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/pomodoro.db
    networks:
      - pomodoro-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pomodoro-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - pomodoro-net
    restart: unless-stopped

networks:
  pomodoro-net:
    driver: bridge

volumes:
  data:

