using System.ComponentModel.DataAnnotations;

namespace PomodoroAPI.Models;

/// <summary>
/// Represents user settings stored in the database
/// Uses a key-value pair structure for flexible configuration storage
/// </summary>
public class Settings
{
    /// <summary>
    /// Unique identifier for the settings record
    /// Auto-generated by the database
    /// </summary>
    public int Id { get; set; }
    
    /// <summary>
    /// The setting key/name (e.g., "work_duration", "break_duration")
    /// Must be unique across all settings
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Key { get; set; } = string.Empty; // e.g., "work_duration", "break_duration", "long_break_duration"
    
    /// <summary>
    /// The setting value stored as a string
    /// Can be parsed to appropriate types as needed
    /// </summary>
    [Required]
    public string Value { get; set; } = string.Empty; // JSON string or simple value
    
    /// <summary>
    /// Timestamp when the setting was created
    /// Automatically set to current UTC time
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// Timestamp when the setting was last updated
    /// Automatically updated on modifications
    /// </summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
